# Generated by Django 5.2.18 on 2026-10-08 13:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("LOGIN_SUCCESS", "Login Success"),
                            ("LOGIN_FAILURE", "Login Failure"),
                            ("LOGOUT", "Logout"),
                            ("REGISTER", "Register"),
                            ("EMAIL_VERIFIED", "Email Verified"),
                            ("MFA_SETUP", "MFA Setup"),
                            ("MFA_VERIFIED", "MFA Verified"),
                            ("MFA_DISABLED", "MFA Disabled"),
                            (
                                "RECOVERY_CODES_REGENERATED",
                                "Recovery Codes Regenerated",
                            ),
                            ("PASSWORD_CHANGED", "Password Changed"),
                            ("PASSWORD_RESET_REQUESTED", "Password Reset Requested"),
                            ("PASSWORD_RESET_CONFIRMED", "Password Reset Confirmed"),
                            ("ROLE_CHANGED", "Role Changed"),
                            ("PROFILE_UPDATED", "Profile Updated"),
                        ],
                        db_index=True,
                        max_length=64,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=512)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="target_audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "audit log",
                "verbose_name_plural": "audit logs",
                "db_table": "audit_log",
                "ordering": ["-timestamp"],
            },
        ),
    ]
