# Generated by Django 5.2.18 on 2026-10-08 16:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("programs", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "vulnerability_type",
                    models.CharField(
                        choices=[
                            ("rce", "Remote Code Execution (RCE)"),
                            ("sqli", "SQL Injection"),
                            ("xss", "Cross-Site Scripting (XSS)"),
                            ("ssrf", "Server-Side Request Forgery (SSRF)"),
                            ("idor", "Insecure Direct Object Reference (IDOR)"),
                            ("bac", "Broken Access Control"),
                            ("auth_bypass", "Authentication Bypass"),
                            ("csrf", "Cross-Site Request Forgery (CSRF)"),
                            ("info_disclosure", "Information Disclosure"),
                            ("open_redirect", "Open Redirect"),
                            ("business_logic", "Business Logic Vulnerability"),
                            ("other", "Other Vulnerability"),
                        ],
                        default="other",
                        max_length=64,
                    ),
                ),
                ("description", models.TextField()),
                ("steps_to_reproduce", models.TextField()),
                ("impact", models.TextField()),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        help_text="Hunter-suggested initial severity",
                        max_length=20,
                    ),
                ),
                (
                    "triaged_severity",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        help_text="Company-assigned triaged severity",
                        max_length=20,
                        null=True,
                    ),
                ),
                ("cvss_vector", models.CharField(blank=True, max_length=128)),
                (
                    "cvss_score",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=3, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("triaged", "Triaged"),
                            ("needs_info", "Needs More Info"),
                            ("accepted", "Accepted"),
                            ("duplicate", "Duplicate"),
                            ("rejected", "Rejected"),
                            ("informative", "Informative"),
                            ("fixed", "Fixed"),
                            ("rewarded", "Rewarded"),
                            ("closed", "Closed"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        db_index=True,
                        default="new",
                        max_length=32,
                    ),
                ),
                ("closed_reason", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "duplicate_of",
                    models.ForeignKey(
                        blank=True,
                        help_text="Original report if marked as duplicate",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="duplicates",
                        to="reports.report",
                    ),
                ),
                (
                    "hunter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submitted_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="programs.program",
                    ),
                ),
                (
                    "target_asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reports",
                        to="programs.programscope",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReportComment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("shared", "Shared with Hunter"),
                            ("internal", "Company Internal Only"),
                        ],
                        db_index=True,
                        default="shared",
                        max_length=20,
                    ),
                ),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="reports.report",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReportEvidence",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("file_key", models.CharField(max_length=255, unique=True)),
                ("original_filename", models.CharField(max_length=255)),
                ("file_size", models.BigIntegerField()),
                ("mime_type", models.CharField(max_length=128)),
                ("sha256_hash", models.CharField(max_length=64)),
                (
                    "scan_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Scan"),
                            ("clean", "Clean"),
                            ("infected", "Infected"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence",
                        to="reports.report",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uploaded_evidence",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReportStatusHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "from_status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("triaged", "Triaged"),
                            ("needs_info", "Needs More Info"),
                            ("accepted", "Accepted"),
                            ("duplicate", "Duplicate"),
                            ("rejected", "Rejected"),
                            ("informative", "Informative"),
                            ("fixed", "Fixed"),
                            ("rewarded", "Rewarded"),
                            ("closed", "Closed"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "to_status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("triaged", "Triaged"),
                            ("needs_info", "Needs More Info"),
                            ("accepted", "Accepted"),
                            ("duplicate", "Duplicate"),
                            ("rejected", "Rejected"),
                            ("informative", "Informative"),
                            ("fixed", "Fixed"),
                            ("rewarded", "Rewarded"),
                            ("closed", "Closed"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        max_length=32,
                    ),
                ),
                ("reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="status_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_history",
                        to="reports.report",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
